// GitHub API Integration

const GITHUB_API_URL = 'https://api.github.com';

interface GitHubRepository {
  id: number;
  name: string;
  full_name: string;
  html_url: string;
  clone_url: string;
  description?: string;
  private: boolean;
}

interface CreateRepoRequest {
  name: string;
  description?: string;
  private?: boolean;
  auto_init?: boolean;
}

interface GitHubFile {
  path: string;
  content: string;
  encoding?: 'utf-8' | 'base64';
}

export class GitHubClient {
  private token: string;
  
  constructor(token: string) {
    this.token = token;
  }
  
  private async request<T>(
    endpoint: string,
    options: RequestInit = {}
  ): Promise<T> {
    const response = await fetch(`${GITHUB_API_URL}${endpoint}`, {
      ...options,
      headers: {
        'Authorization': `Bearer ${this.token}`,
        'Accept': 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        ...options.headers
      }
    });
    
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`GitHub API Error: ${response.status} - ${error}`);
    }
    
    return response.json();
  }
  
  async getUser(): Promise<{ login: string; name: string; email: string }> {
    return this.request('/user');
  }
  
  async getRepositories(): Promise<GitHubRepository[]> {
    return this.request('/user/repos?per_page=100');
  }
  
  async createRepository(data: CreateRepoRequest): Promise<GitHubRepository> {
    return this.request('/user/repos', {
      method: 'POST',
      body: JSON.stringify({
        name: data.name,
        description: data.description,
        private: data.private ?? false,
        auto_init: data.auto_init ?? true
      })
    });
  }
  
  async createFile(
    owner: string,
    repo: string,
    path: string,
    content: string,
    message: string
  ): Promise<{ commit: { sha: string }; content: { sha: string } }> {
    return this.request(`/repos/${owner}/${repo}/contents/${path}`, {
      method: 'PUT',
      body: JSON.stringify({
        message,
        content: Buffer.from(content).toString('base64')
      })
    });
  }
  
  async createMultipleFiles(
    owner: string,
    repo: string,
    files: GitHubFile[],
    commitMessage: string
  ): Promise<{ success: boolean; count: number }> {
    let count = 0;
    
    for (const file of files) {
      try {
        await this.createFile(owner, repo, file.path, file.content, `${commitMessage}: ${file.path}`);
        count++;
      } catch (error) {
        console.error(`Failed to create file ${file.path}:`, error);
      }
    }
    
    return { success: true, count };
  }
  
  async getRepository(owner: string, repo: string): Promise<GitHubRepository> {
    return this.request(`/repos/${owner}/${repo}`);
  }
  
  async deleteRepository(owner: string, repo: string): Promise<void> {
    await this.request(`/repos/${owner}/${repo}`, {
      method: 'DELETE'
    });
  }
}

// Singleton instance
let githubClient: GitHubClient | null = null;

export function getGitHubClient(): GitHubClient {
  if (!githubClient) {
    const token = process.env.GITHUB_TOKEN;
    if (!token) {
      throw new Error('GITHUB_TOKEN is not configured');
    }
    githubClient = new GitHubClient(token);
  }
  return githubClient;
}

export async function createProjectRepository(
  projectName: string,
  files: Array<{ path: string; content: string }>,
  description?: string
): Promise<{
  success: boolean;
  repository?: GitHubRepository;
  error?: string;
}> {
  try {
    const client = getGitHubClient();
    const user = await client.getUser();
    
    // Create repository
    const repo = await client.createRepository({
      name: projectName,
      description: description || `Generated by AI Code Creator - ${projectName}`,
      private: false,
      auto_init: true
    });
    
    // Add files
    await client.createMultipleFiles(
      user.login,
      projectName,
      files,
      'Initial commit from AI Code Creator'
    );
    
    return {
      success: true,
      repository: repo
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to create repository'
    };
  }
}
