// Northflank API Integration

const NORTHFLANK_API_URL = 'https://api.northflank.com/v1';

interface NorthflankProject {
  id: string;
  name: string;
  description?: string;
  subDomain?: string;
}

interface NorthflankService {
  id: string;
  name: string;
  projectId: string;
  status: string;
  url?: string;
}

interface CreateProjectRequest {
  name: string;
  description?: string;
  subDomain?: string;
}

interface CreateServiceRequest {
  name: string;
  projectId: string;
  dockerImage?: string;
  buildSettings?: {
    dockerfile: string;
    buildArgs?: Record<string, string>;
  };
  deployment?: {
    replicas: number;
    externalDNS: string[];
  };
}

export class NorthflankClient {
  private apiToken: string;
  
  constructor(apiToken: string) {
    this.apiToken = apiToken;
  }
  
  private async request<T>(
    endpoint: string,
    options: RequestInit = {}
  ): Promise<T> {
    const response = await fetch(`${NORTHFLANK_API_URL}${endpoint}`, {
      ...options,
      headers: {
        'Authorization': `Bearer ${this.apiToken}`,
        'Content-Type': 'application/json',
        ...options.headers
      }
    });
    
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Northflank API Error: ${response.status} - ${error}`);
    }
    
    return response.json();
  }
  
  async getProjects(): Promise<NorthflankProject[]> {
    const result = await this.request<{ projects: NorthflankProject[] }>('/projects');
    return result.projects;
  }
  
  async createProject(data: CreateProjectRequest): Promise<NorthflankProject> {
    return this.request<NorthflankProject>('/projects', {
      method: 'POST',
      body: JSON.stringify(data)
    });
  }
  
  async getProject(projectId: string): Promise<NorthflankProject> {
    return this.request<NorthflankProject>(`/projects/${projectId}`);
  }
  
  async createService(data: CreateServiceRequest): Promise<NorthflankService> {
    return this.request<NorthflankService>(`/projects/${data.projectId}/services`, {
      method: 'POST',
      body: JSON.stringify({
        name: data.name,
        buildSettings: data.buildSettings,
        deployment: data.deployment
      })
    });
  }
  
  async deployService(projectId: string, serviceId: string): Promise<{ success: boolean }> {
    return this.request(`/projects/${projectId}/services/${serviceId}/deploy`, {
      method: 'POST'
    });
  }
  
  async getServiceStatus(projectId: string, serviceId: string): Promise<{
    status: string;
    url?: string;
    logs?: string[];
  }> {
    return this.request(`/projects/${projectId}/services/${serviceId}/status`);
  }
  
  async addCustomDomain(projectId: string, serviceId: string, domain: string): Promise<{
    success: boolean;
    domain: string;
    verificationRecords: Array<{
      type: string;
      name: string;
      value: string;
    }>;
  }> {
    return this.request(`/projects/${projectId}/services/${serviceId}/domains`, {
      method: 'POST',
      body: JSON.stringify({ domain })
    });
  }
}

// Singleton instance
let northflankClient: NorthflankClient | null = null;

export function getNorthflankClient(): NorthflankClient {
  if (!northflankClient) {
    const token = process.env.NORTHFLANK_API_TOKEN;
    if (!token) {
      throw new Error('NORTHFLANK_API_TOKEN is not configured');
    }
    northflankClient = new NorthflankClient(token);
  }
  return northflankClient;
}

export async function deployToNorthflank(
  projectName: string,
  dockerImage: string,
  domain?: string
): Promise<{
  success: boolean;
  projectId?: string;
  serviceId?: string;
  url?: string;
  error?: string;
}> {
  try {
    const client = getNorthflankClient();
    
    // Create project
    const project = await client.createProject({
      name: projectName,
      description: `Generated by AI Code Creator - ${projectName}`,
      subDomain: projectName.toLowerCase().replace(/[^a-z0-9]/g, '-')
    });
    
    // Create service
    const service = await client.createService({
      name: `${projectName}-service`,
      projectId: project.id,
      dockerImage,
      deployment: {
        replicas: 1,
        externalDNS: domain ? [domain] : []
      }
    });
    
    // Deploy
    await client.deployService(project.id, service.id);
    
    // Add custom domain if provided
    if (domain) {
      await client.addCustomDomain(project.id, service.id, domain);
    }
    
    return {
      success: true,
      projectId: project.id,
      serviceId: service.id,
      url: `https://${project.subDomain}.northflank.app`
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Deployment failed'
    };
  }
}
