import { Template, ProjectTemplate } from '@/types';

export const templates: Template[] = [
  {
    id: 'nextjs-dashboard',
    name: 'Dashboard',
    nameAr: 'لوحة تحكم',
    description: 'Modern admin dashboard with charts, tables, and analytics',
    descriptionAr: 'لوحة تحكم إدارية حديثة مع رسوم بيانية وجداول وتحليلات',
    icon: 'LayoutDashboard',
    features: ['Charts & Analytics', 'Data Tables', 'User Management', 'Dark Mode'],
    featuresAr: ['رسوم بيانية وتحليلات', 'جداول بيانات', 'إدارة المستخدمين', 'الوضع الداكن'],
    defaultFiles: []
  },
  {
    id: 'nextjs-landing',
    name: 'Landing Page',
    nameAr: 'صفحة هبوط',
    description: 'Beautiful landing page with hero section, features, and CTA',
    descriptionAr: 'صفحة هبوط جميلة مع قسم رئيسي وميزات ودعوة للعمل',
    icon: 'Rocket',
    features: ['Hero Section', 'Features Grid', 'Testimonials', 'Contact Form'],
    featuresAr: ['قسم رئيسي', 'شبكة الميزات', 'آراء العملاء', 'نموذج اتصال'],
    defaultFiles: []
  },
  {
    id: 'nextjs-ecommerce',
    name: 'E-Commerce',
    nameAr: 'متجر إلكتروني',
    description: 'Full-featured online store with cart and checkout',
    descriptionAr: 'متجر إلكتروني متكامل مع سلة وشراء',
    icon: 'ShoppingCart',
    features: ['Product Catalog', 'Shopping Cart', 'Checkout Flow', 'Order Management'],
    featuresAr: ['كتالوج المنتجات', 'سلة التسوق', 'عملية الشراء', 'إدارة الطلبات'],
    defaultFiles: []
  },
  {
    id: 'nextjs-blog',
    name: 'Blog',
    nameAr: 'مدونة',
    description: 'Modern blog with MDX support and beautiful typography',
    descriptionAr: 'مدونة حديثة مع دعم MDX وطباعة جميلة',
    icon: 'FileText',
    features: ['MDX Support', 'Categories & Tags', 'Author Profiles', 'SEO Optimized'],
    featuresAr: ['دعم MDX', 'التصنيفات والوسوم', 'ملفات المؤلفين', 'محسّن لمحركات البحث'],
    defaultFiles: []
  },
  {
    id: 'nextjs-saas',
    name: 'SaaS App',
    nameAr: 'تطبيق SaaS',
    description: 'Software as a Service template with pricing and subscriptions',
    descriptionAr: 'قالب البرمجيات كخدمة مع الأسعار والاشتراكات',
    icon: 'Cloud',
    features: ['Pricing Plans', 'User Authentication', 'Subscription Management', 'API Integration'],
    featuresAr: ['خطط الأسعار', 'مصادقة المستخدم', 'إدارة الاشتراكات', 'تكامل API'],
    defaultFiles: []
  },
  {
    id: 'nextjs-portfolio',
    name: 'Portfolio',
    nameAr: 'معرض أعمال',
    description: 'Professional portfolio to showcase your work',
    descriptionAr: 'معرض أعمال احترافي لعرض أعمالك',
    icon: 'Briefcase',
    features: ['Project Gallery', 'About Section', 'Skills Display', 'Contact Form'],
    featuresAr: ['معرض المشاريع', 'قسم عني', 'عرض المهارات', 'نموذج اتصال'],
    defaultFiles: []
  },
  {
    id: 'custom',
    name: 'Custom Project',
    nameAr: 'مشروع مخصص',
    description: 'Start from scratch with your own requirements',
    descriptionAr: 'ابدأ من الصفر بمتطلباتك الخاصة',
    icon: 'Sparkles',
    features: ['Full Customization', 'Any Framework', 'Your Stack', 'Complete Control'],
    featuresAr: ['تخصيص كامل', 'أي إطار عمل', 'مكدسك الخاص', 'تحكم كامل'],
    defaultFiles: []
  }
];

export function getTemplate(id: ProjectTemplate): Template | undefined {
  return templates.find(t => t.id === id);
}

export function generateProjectFiles(template: ProjectTemplate, projectName: string): string {
  const baseFiles = `
# ${projectName}

Generated by AI Code Creator

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

## Project Structure

\`\`\`
${projectName}/
├── src/
│   ├── app/
│   ├── components/
│   └── lib/
├── public/
└── package.json
\`\`\`
`;

  return baseFiles;
}
