import { NextRequest, NextResponse } from 'next/server';
import { createAICompletion } from '@/lib/ai-providers';
import { templates, getTemplate } from '@/lib/templates';
import { ProjectTemplate, ProjectFile } from '@/types';
import { v4 as uuidv4 } from 'uuid';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

interface GenerateRequest {
  prompt: string;
  template: ProjectTemplate;
  projectName: string;
  provider?: string;
}

function generateDefaultFiles(projectName: string, template: ProjectTemplate): ProjectFile[] {
  const baseFiles: ProjectFile[] = [
    {
      id: uuidv4(),
      name: 'package.json',
      path: 'package.json',
      type: 'file',
      content: JSON.stringify({
        name: projectName.toLowerCase().replace(/\s+/g, '-'),
        version: '0.1.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
          lint: 'next lint'
        },
        dependencies: {
          next: '^15.0.0',
          react: '^19.0.0',
          'react-dom': '^19.0.0',
          typescript: '^5.0.0',
          tailwindcss: '^4.0.0',
          '@radix-ui/react-slot': '^1.0.0',
          'class-variance-authority': '^0.7.0',
          clsx: '^2.0.0',
          'tailwind-merge': '^3.0.0'
        },
        devDependencies: {
          '@types/node': '^20.0.0',
          '@types/react': '^19.0.0',
          '@types/react-dom': '^19.0.0',
          eslint: '^9.0.0',
          'eslint-config-next': '^15.0.0'
        }
      }, null, 2),
      language: 'json'
    },
    {
      id: uuidv4(),
      name: 'tsconfig.json',
      path: 'tsconfig.json',
      type: 'file',
      content: JSON.stringify({
        compilerOptions: {
          target: 'ES2017',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          plugins: [{ name: 'next' }],
          paths: {
            '@/*': ['./src/*']
          }
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
        exclude: ['node_modules']
      }, null, 2),
      language: 'json'
    },
    {
      id: uuidv4(),
      name: 'next.config.ts',
      path: 'next.config.ts',
      type: 'file',
      content: `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /* config options here */
};

export default nextConfig;`,
      language: 'typescript'
    },
    {
      id: uuidv4(),
      name: 'tailwind.config.ts',
      path: 'tailwind.config.ts',
      type: 'file',
      content: `import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};

export default config;`,
      language: 'typescript'
    },
    {
      id: uuidv4(),
      name: 'postcss.config.mjs',
      path: 'postcss.config.mjs',
      type: 'file',
      content: `/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    tailwindcss: {},
  },
};

export default config;`,
      language: 'javascript'
    },
    {
      id: uuidv4(),
      name: 'globals.css',
      path: 'src/app/globals.css',
      type: 'file',
      content: `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: #ffffff;
  --foreground: #171717;
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}

body {
  color: var(--foreground);
  background: var(--background);
  font-family: Arial, Helvetica, sans-serif;
}`,
      language: 'css'
    },
    {
      id: uuidv4(),
      name: 'layout.tsx',
      path: 'src/app/layout.tsx',
      type: 'file',
      content: `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${projectName}",
  description: "Generated by AI Code Creator",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}`,
      language: 'typescript'
    }
  ];

  // Add template-specific files
  const templateInfo = getTemplate(template);
  
  let pageContent = '';
  
  switch (template) {
    case 'nextjs-dashboard':
      pageContent = `export default function Dashboard() {
  return (
    <main className="min-h-screen p-8">
      <div className="max-w-7xl mx-auto">
        <h1 className="text-3xl font-bold mb-8">Dashboard</h1>
        
        {/* Stats Cards */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
          {[
            { title: 'Total Users', value: '2,350', change: '+12%' },
            { title: 'Revenue', value: '$45,231', change: '+8%' },
            { title: 'Orders', value: '1,234', change: '+23%' },
            { title: 'Conversion', value: '3.2%', change: '+2%' },
          ].map((stat, i) => (
            <div key={i} className="bg-card rounded-lg p-6 border">
              <p className="text-sm text-muted-foreground">{stat.title}</p>
              <p className="text-2xl font-bold">{stat.value}</p>
              <p className="text-xs text-green-500">{stat.change}</p>
            </div>
          ))}
        </div>
        
        {/* Main Content */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="lg:col-span-2 bg-card rounded-lg p-6 border">
            <h2 className="text-xl font-semibold mb-4">Analytics Overview</h2>
            <div className="h-64 flex items-center justify-center text-muted-foreground">
              Chart Placeholder
            </div>
          </div>
          <div className="bg-card rounded-lg p-6 border">
            <h2 className="text-xl font-semibold mb-4">Recent Activity</h2>
            <div className="space-y-4">
              {[1, 2, 3, 4, 5].map((i) => (
                <div key={i} className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-full bg-primary/10" />
                  <div className="flex-1">
                    <p className="text-sm">Activity item {i}</p>
                    <p className="text-xs text-muted-foreground">2 min ago</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}`;
      break;
      
    case 'nextjs-landing':
      pageContent = `export default function Landing() {
  return (
    <main className="min-h-screen">
      {/* Hero Section */}
      <section className="relative h-screen flex items-center justify-center bg-gradient-to-br from-blue-600 to-purple-700">
        <div className="text-center text-white px-4">
          <h1 className="text-5xl md:text-7xl font-bold mb-6">
            Welcome to ${projectName}
          </h1>
          <p className="text-xl md:text-2xl mb-8 max-w-2xl mx-auto">
            Build amazing products with our cutting-edge solution
          </p>
          <div className="flex gap-4 justify-center">
            <button className="px-8 py-3 bg-white text-blue-600 rounded-lg font-semibold hover:bg-gray-100 transition">
              Get Started
            </button>
            <button className="px-8 py-3 border border-white rounded-lg font-semibold hover:bg-white/10 transition">
              Learn More
            </button>
          </div>
        </div>
      </section>
      
      {/* Features Section */}
      <section className="py-20 px-4">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-12">Features</h2>
          <div className="grid md:grid-cols-3 gap-8">
            {[
              { title: 'Fast', desc: 'Lightning fast performance' },
              { title: 'Secure', desc: 'Enterprise-grade security' },
              { title: 'Scalable', desc: 'Scale with your business' },
            ].map((feature, i) => (
              <div key={i} className="text-center p-6 rounded-xl border">
                <h3 className="text-xl font-semibold mb-2">{feature.title}</h3>
                <p className="text-muted-foreground">{feature.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
      
      {/* CTA Section */}
      <section className="py-20 px-4 bg-gray-50">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-3xl font-bold mb-4">Ready to get started?</h2>
          <p className="text-muted-foreground mb-8">
            Join thousands of satisfied customers today
          </p>
          <button className="px-8 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition">
            Start Free Trial
          </button>
        </div>
      </section>
    </main>
  );
}`;
      break;
      
    case 'nextjs-ecommerce':
      pageContent = `export default function Store() {
  const products = [
    { id: 1, name: 'Product 1', price: 99.99, image: '/product1.jpg' },
    { id: 2, name: 'Product 2', price: 149.99, image: '/product2.jpg' },
    { id: 3, name: 'Product 3', price: 79.99, image: '/product3.jpg' },
    { id: 4, name: 'Product 4', price: 199.99, image: '/product4.jpg' },
  ];
  
  return (
    <main className="min-h-screen">
      {/* Header */}
      <header className="border-b sticky top-0 bg-white z-50">
        <div className="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between">
          <h1 className="text-2xl font-bold">${projectName}</h1>
          <nav className="flex gap-6">
            <a href="#" className="hover:text-blue-600">Products</a>
            <a href="#" className="hover:text-blue-600">Categories</a>
            <a href="#" className="hover:text-blue-600">About</a>
          </nav>
          <button className="px-4 py-2 bg-black text-white rounded-lg">
            Cart (0)
          </button>
        </div>
      </header>
      
      {/* Hero */}
      <section className="bg-gray-100 py-20 text-center">
        <h2 className="text-4xl font-bold mb-4">Summer Sale</h2>
        <p className="text-muted-foreground mb-6">Up to 50% off on selected items</p>
        <button className="px-6 py-3 bg-black text-white rounded-lg">
          Shop Now
        </button>
      </section>
      
      {/* Products */}
      <section className="max-w-7xl mx-auto px-4 py-12">
        <h2 className="text-2xl font-bold mb-8">Featured Products</h2>
        <div className="grid md:grid-cols-4 gap-6">
          {products.map((product) => (
            <div key={product.id} className="border rounded-lg overflow-hidden hover:shadow-lg transition">
              <div className="h-48 bg-gray-200" />
              <div className="p-4">
                <h3 className="font-semibold">{product.name}</h3>
                <p className="text-lg font-bold">\${product.price}</p>
                <button className="mt-2 w-full py-2 bg-black text-white rounded">
                  Add to Cart
                </button>
              </div>
            </div>
          ))}
        </div>
      </section>
    </main>
  );
}`;
      break;
      
    case 'nextjs-blog':
      pageContent = `export default function Blog() {
  const posts = [
    { id: 1, title: 'Getting Started with Next.js', excerpt: 'Learn the basics...', date: 'Jan 15, 2025' },
    { id: 2, title: 'Advanced TypeScript Tips', excerpt: 'Master TypeScript...', date: 'Jan 10, 2025' },
    { id: 3, title: 'Building Scalable Apps', excerpt: 'Best practices...', date: 'Jan 5, 2025' },
  ];
  
  return (
    <main className="min-h-screen">
      {/* Header */}
      <header className="border-b">
        <div className="max-w-4xl mx-auto px-4 py-8">
          <h1 className="text-4xl font-bold">${projectName}</h1>
          <p className="text-muted-foreground mt-2">Thoughts, ideas, and tutorials</p>
        </div>
      </header>
      
      {/* Posts */}
      <section className="max-w-4xl mx-auto px-4 py-12">
        <div className="space-y-8">
          {posts.map((post) => (
            <article key={post.id} className="border-b pb-8">
              <h2 className="text-2xl font-bold hover:text-blue-600 cursor-pointer">
                {post.title}
              </h2>
              <p className="text-muted-foreground mt-2">{post.excerpt}</p>
              <p className="text-sm text-muted-foreground mt-2">{post.date}</p>
            </article>
          ))}
        </div>
      </section>
      
      {/* Footer */}
      <footer className="border-t py-8">
        <div className="max-w-4xl mx-auto px-4 text-center text-muted-foreground">
          © 2025 ${projectName}. All rights reserved.
        </div>
      </footer>
    </main>
  );
}`;
      break;
      
    case 'nextjs-saas':
      pageContent = `export default function SaaS() {
  const pricingPlans = [
    { name: 'Starter', price: 9, features: ['5 Projects', '10GB Storage', 'Email Support'] },
    { name: 'Pro', price: 29, features: ['Unlimited Projects', '100GB Storage', 'Priority Support', 'API Access'] },
    { name: 'Enterprise', price: 99, features: ['Everything in Pro', 'Custom Integrations', 'Dedicated Support', 'SLA'] },
  ];
  
  return (
    <main className="min-h-screen">
      {/* Hero */}
      <section className="py-20 px-4 text-center bg-gradient-to-br from-indigo-600 to-purple-700 text-white">
        <h1 className="text-5xl font-bold mb-4">Supercharge Your Workflow</h1>
        <p className="text-xl mb-8 max-w-2xl mx-auto">
          The all-in-one platform for modern teams to collaborate and ship faster
        </p>
        <button className="px-8 py-3 bg-white text-indigo-600 rounded-lg font-semibold">
          Start Free Trial
        </button>
      </section>
      
      {/* Pricing */}
      <section className="py-20 px-4">
        <div className="max-w-5xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-12">Simple Pricing</h2>
          <div className="grid md:grid-cols-3 gap-8">
            {pricingPlans.map((plan, i) => (
              <div key={i} className={\`border rounded-xl p-6 \${i === 1 ? 'border-indigo-500 shadow-lg' : ''}\`}>
                <h3 className="text-xl font-semibold">{plan.name}</h3>
                <p className="text-4xl font-bold my-4">\${plan.price}<span className="text-lg text-muted-foreground">/mo</span></p>
                <ul className="space-y-2 mb-6">
                  {plan.features.map((f, j) => (
                    <li key={j} className="flex items-center gap-2">
                      <span className="text-green-500">✓</span> {f}
                    </li>
                  ))}
                </ul>
                <button className={\`w-full py-2 rounded-lg \${i === 1 ? 'bg-indigo-600 text-white' : 'border'}\`}>
                  Get Started
                </button>
              </div>
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}`;
      break;
      
    case 'nextjs-portfolio':
      pageContent = `export default function Portfolio() {
  const projects = [
    { id: 1, title: 'Project 1', category: 'Web Design' },
    { id: 2, title: 'Project 2', category: 'Mobile App' },
    { id: 3, title: 'Project 3', category: 'Branding' },
  ];
  
  return (
    <main className="min-h-screen">
      {/* Hero */}
      <section className="py-20 px-4">
        <div className="max-w-4xl mx-auto text-center">
          <h1 className="text-5xl font-bold mb-4">Hi, I'm ${projectName}</h1>
          <p className="text-xl text-muted-foreground">
            A creative developer crafting beautiful digital experiences
          </p>
        </div>
      </section>
      
      {/* Projects */}
      <section className="py-20 px-4 bg-gray-50">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold mb-12 text-center">My Work</h2>
          <div className="grid md:grid-cols-3 gap-6">
            {projects.map((project) => (
              <div key={project.id} className="bg-white rounded-xl overflow-hidden shadow-sm hover:shadow-lg transition">
                <div className="h-48 bg-gray-200" />
                <div className="p-4">
                  <p className="text-sm text-muted-foreground">{project.category}</p>
                  <h3 className="text-lg font-semibold">{project.title}</h3>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
      
      {/* Contact */}
      <section className="py-20 px-4">
        <div className="max-w-xl mx-auto text-center">
          <h2 className="text-3xl font-bold mb-4">Let's Work Together</h2>
          <p className="text-muted-foreground mb-6">
            Have a project in mind? Let's create something amazing
          </p>
          <button className="px-8 py-3 bg-black text-white rounded-lg">
            Get in Touch
          </button>
        </div>
      </section>
    </main>
  );
}`;
      break;
      
    default:
      pageContent = `export default function Home() {
  return (
    <main className="min-h-screen flex items-center justify-center">
      <div className="text-center">
        <h1 className="text-4xl font-bold mb-4">Welcome to ${projectName}</h1>
        <p className="text-muted-foreground">Start building your amazing project</p>
      </div>
    </main>
  );
}`;
  }
  
  baseFiles.push({
    id: uuidv4(),
    name: 'page.tsx',
    path: 'src/app/page.tsx',
    type: 'file',
    content: pageContent,
    language: 'typescript'
  });
  
  // Add Dockerfile
  baseFiles.push({
    id: uuidv4(),
    name: 'Dockerfile',
    path: 'Dockerfile',
    type: 'file',
    content: `FROM node:20-alpine AS base

# Install dependencies only when needed
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run build

# Production image
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]`,
    language: 'dockerfile'
  });
  
  // Add .dockerignore
  baseFiles.push({
    id: uuidv4(),
    name: '.dockerignore',
    path: '.dockerignore',
    type: 'file',
    content: `node_modules
.next
.git
.gitignore
README.md
.env*
.DS_Store`,
    language: 'plaintext'
  });
  
  // Add README
  baseFiles.push({
    id: uuidv4(),
    name: 'README.md',
    path: 'README.md',
    type: 'file',
    content: `# ${projectName}

Generated by AI Code Creator

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) to see the result.

## Deployment

This project is containerized with Docker for easy deployment.

\`\`\`bash
docker build -t ${projectName.toLowerCase().replace(/\s+/g, '-')} .
docker run -p 3000:3000 ${projectName.toLowerCase().replace(/\s+/g, '-')}
\`\`\`
`,
    language: 'markdown'
  });
  
  return baseFiles;
}

export async function POST(request: NextRequest) {
  try {
    const body: GenerateRequest = await request.json();
    const { prompt, template, projectName, provider = 'zai' } = body;
    
    if (!prompt) {
      return NextResponse.json(
        { error: 'Prompt is required' },
        { status: 400 }
      );
    }
    
    // Generate project files
    const files = generateDefaultFiles(projectName || 'my-project', template);
    
    // Use AI to enhance the project based on the prompt
    const aiPrompt = `Generate a Next.js 15 application based on the following requirements:

Project Name: ${projectName}
Template: ${template}
Requirements: ${prompt}

The project should include:
1. A modern, responsive UI using Tailwind CSS
2. TypeScript with strict mode
3. Clean, maintainable code structure
4. Proper error handling

Please provide any additional code suggestions or improvements.`;

    const aiResult = await createAICompletion(
      provider as 'grok' | 'openrouter' | 'zai',
      [
        { role: 'user', content: aiPrompt }
      ],
      { temperature: 0.7 }
    );
    
    // Create project object
    const project = {
      id: uuidv4(),
      name: projectName || 'my-project',
      description: prompt,
      files,
      template,
      status: 'ready' as const,
      createdAt: new Date(),
      updatedAt: new Date()
    };
    
    return NextResponse.json({
      success: true,
      project,
      aiSuggestions: aiResult.success ? aiResult.content : null
    });
    
  } catch (error) {
    console.error('Generate API Error:', error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Internal server error' },
      { status: 500 }
    );
  }
}
